---
documentclass: article
geometry:
- top=2cm
- right=2cm
- bottom=2cm
- left=2cm
papersize: a4
fontsize: 12pt
toc: true
numbersections: true
linkcolor: blue
lang: fr-FR
author:
- Justin Bossard
- Antoine Feuillette
...
